int16 elevator_control
int32 lower_linear_module_control
int32 upper_linear_module_control
int16[12] snake_control_1_array  # 固定长度为12的int16数组
int16[12] snake_control_2_array  # 固定长度为12的int16数组

int16 pull_push_sensors_reset # reset control for pull push sensors
int16 elevator_counter_reset # reset elevator counter
int16 lower_linear_module_encorder_reset # reset lower_linear_module_encorder
int16 upper_linear_module_encorder_reset # reset upper_linear_module_encorder
