int32[12] snake_motor_encorder_position_1 # motor encorder of snake 1 (65536 pulses per rotation)
int16 gripper_gm6020_position_1 # gm6020 position feedback (360 per round)
int16 gripper_c610_position_1   # c610 position feedback (360*36 per round, the reduction ratio is 36:1)
int16 gripper_sts3032_position_1 # sts3032 position feedback (360 per round)
int16 robomaster_1_reset # Reset state for robomaster 1 motor encorders