#  Copyright Copyright (C) 2001-2021 Force Dimension, Switzerland.
#  All Rights Reserved.
#
#  Force Dimension SDK 3.14.0

# Eigen dependency
EIGEN      = $(TOP_DIR)/externals/Eigen
CXXFLAGS += -I$(EIGEN)

# GLFW dependency
LDLIBS += -lglfw
